2 Semester/WebLabs/WebMinimalAppLab/Models/Calculation.cs
namespace WebMinimalAppLab.Models
{
    public class Calculation
    {
        public Calculation(int a, int b) 
        {
            Doable = true;

            ValueOne = a;
            ValueTwo = b;

            Sum = a + b;
            Mult = a * b;

            if (b != 0)
            { Div = a / b; }
            else Doable = false;

            Sub = a - b;
        }
        public Calculation()
        {
            Doable = true;

            var Rand = new Random();
            int Num1 = Rand.Next(10);
            int Num2 = Rand.Next(10);


            ValueOne = Num1;
            ValueTwo = Num2;
            Sum = Num1 + Num2;
            Mult = Num1 * Num2;
            Sub = Num1 - Num2;
            Div = 0;

            if (Num2 == 0) Doable = false;
            else 
                Div = Num1/ Num2;

        }
        public int ValueOne { get; set; }
        public int ValueTwo { get; set; }
        private int Helper { get; set; }
        public bool Doable { get; set; }

        public int Sum { get; set; }
        public int Mult { get; set; }
        public int Div { get; set; }
        public int Sub { get; set; }

    }
}

2 Semester/WebLabs/WebMinimalAppLab/Models/ErrorViewModel.cs
namespace WebMinimalAppLab.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

2 Semester/WebLabs/WebMinimalAppLab/Controllers/CalculationsController.cs
using Microsoft.AspNetCore.Mvc;
using WebMinimalAppLab.Models;

namespace WebMinimalAppLab.Controllers
{
    public class CalculationsController : Controller
    {
        public IActionResult UsingInjection()
        {
            return View();
        }
        public IActionResult UsingDataBag()
        {
            ViewBag.Calcululus = new Calculation();
            return View();
        }

        public IActionResult UsingViewData()
        {
            ViewData["Calc"] = new Calculation();
            return View();
        }

        public IActionResult UsingModel()
        {
            var Calc = new Calculation();
            return View(Calc);
        }
    }
}

2 Semester/WebLabs/WebMinimalAppLab/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebMinimalAppLab.Models;

namespace WebMinimalAppLab.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

2 Semester/WebLabs/WebMinimalAppLab/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div>
    <h1>Calc Service Demonstration</h1>
    <ul>
        <li>
             <a asp-controller="Calculations" asp-action="UsingModel">Using Model Calc</a>
        </li>
        <li>
            <a asp-controller="Calculations" asp-action="UsingViewData">Using ViewData Calc</a>
        </li>
        <li>
            <a asp-controller="Calculations" asp-action="UsingDataBag">Using ViewBag Calc</a>
        </li>
        <li>
            <a asp-controller="Calculations" asp-action="UsingInjection">Using Service Injection Calc</a>
        </li>
    </ul>
</div>

2 Semester/WebLabs/WebMinimalAppLab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMinimalAppLab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebMinimalAppLab.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">WebMinimalAppLab</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebMinimalAppLab - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>